export const GET_PRODUCT_INITIATE = 'GET_PRODUCT_INITIATE'
export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE'
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'

export const GET_PRODUCTBYID_INITIATE = 'GET_PRODUCTBYID_INITIATE'
export const GET_PRODUCTBYID_FAILURE = 'GET_PRODUCTBYID_FAILURE'
export const GET_PRODUCTBYID_SUCCESS = 'GET_PRODUCTBYID_SUCCESS'

// const GET_PRODUCT_INITIATE = 'GET_PRODUCT_INITIATE'
// const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE'
// const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'

// module.exports={
//     GET_PRODUCT_INITIATE,
//     GET_PRODUCT_FAILURE,
//     GET_PRODUCT_SUCCESS
// }